apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: fargate-nginx-template
  title: Nginx Fargate Web Service
  description: Create a simple website using Nginx and AWS Fargate
  tags:
    - recommended
    - nginx
    - fargate
spec:
  owner: service@example.com
  type: service

  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
        - initial_message
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        initial_message:
          title: Initial message
          type: string
          description: Initial message to display on the website ('Hello world!')
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          initial_message: ${{ parameters.initial_message }}
          owner: ${{ parameters.owner }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          http_port: 8080
          # The AWS Proton environments to use for deploying the initial service instances
          aws_proton_dev_environment_name: "multi-svc-beta"
          aws_proton_prod_environment_name: "multi-svc-beta"
          # The AWS account where the Proton service will be created
          aws_account_id: "508282329626"
          # The AWS region where the Proton service will be created
          aws_region: eu-west-1

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: private
        defaultBranch: main
        sourcePath: ./repo-contents

    - id: create-proton-service
      name: Create AWS Proton Service
      action: aws:proton:create-service
      input:
        serviceName: ${{ parameters.component_id }}
        repository: ${{ parameters.repoUrl | parseRepoUrl }}
        branchName: main
        serviceSpecPath: ./spec.yaml
        # Update the following fields to match the resources in your AWS account
        region: eu-west-1
        templateName: lb-fargate-service
        templateMajorVersion: '1'
        repositoryConnectionArn: 'arn:aws:codestar-connections:eu-west-1:508282329626:connection/d0c5df5c-c171-409c-966c-d3388ad2ad82'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
